name: Publish

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dist:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: make develop

    - name: Make dist
      run: make dist
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - uses: actions/upload-artifact@v4
      with:
        path: ./dist/*.tar.gz
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - uses: actions/upload-artifact@v4
      with:
        path: ./dist/*.whl
